"""
streamer_collector.py — Schwab WebSocket streamer IV update loop

PURPOSE
-------
Subscribes to LEVELONE_OPTIONS for ATM contracts (one per maturity bucket per
ticker) and writes real-time IV updates to iv_intraday_stream DuckDB as each
market-hours push arrives.

The streamer is Phase C: it enhances the REST baseline (Phase A) with intraday
precision. It does NOT replace REST collection — it patches the live iv_30d for
tickers still in the market-hours window.

ARCHITECTURE
------------
REST collector (rest_collector.py) runs once at market open (or on demand):
  → writes the full 8-bucket IV surface to iv_term_history

Streamer collector (this file) runs as a daemon within market hours:
  → receives field 10 (volatility/IV) pushes from LEVELONE_OPTIONS
  → updates iv_30d (and optionally other buckets) in-memory
  → flushes to iv_intraday_stream every FLUSH_INTERVAL_SEC (default: 60s)

ATM DRIFT RE-SUBSCRIPTION
--------------------------
Stock price moves intraday; the subscribed strike can become ITM/OTM.
Every ATM_REFRESH_INTERVAL_MIN minutes a background thread checks each ticker's
current spot price (via SchwabClient.get_quote). If spot has moved more than
ATM_DRIFT_THRESHOLD_PCT from the last known spot, the chain is re-fetched,
new ATM symbols are computed, the old symbols are UNSUBS'd, and the new ones
are SUBS'd — all atomically under _symbol_map_lock.

This ensures IV readings always reflect the true at-the-money contract.

CONTRACT SUBSCRIPTIONS
----------------------
Generated by contract_builder.find_atm_for_buckets_with_ticker().
Format: "AAPL  260225C00265000"  (confirmed from Schwab Streamer API docs + real data)
We subscribe to call-side ATM for the 30-day bucket as the primary IV proxy.
We optionally subscribe to 7d, 60d, 90d buckets for the term-structure update.

SCHWAB STREAMER PROTOCOL (from PDF docs)
-----------------------------------------
1. GET /trader/v1/userPreference → { streamerInfo: [{streamerSocketUrl, schwabClientCustomerId, ...}] }
2. WebSocket connect to streamerSocketUrl
3. Send LOGIN request with credentials
4. Wait for response code 0 (SUCCESS)
5. Send SUBS request for LEVELONE_OPTIONS
6. Receive data frames: {data: [{service: "LEVELONE_OPTIONS", content: [{key: symbol, 10: iv, ...}]}]}
7. Heartbeat frames: {notify: [{heartbeat: "..."}]} — respond with nothing (passive)
8. On connection drop: reconnect with exponential backoff

LEVELONE_OPTIONS fields subscribed:
    1  = description (option symbol)
    8  = Volume
    9  = Open Interest
    10 = Volatility (IV) ← primary field
    27 = Days to Expiration
    28 = Delta

WRITE CONTRACT
--------------
Never writes NULL iv. Only writes a row when a valid IV push arrives.
Flush is batched — one DuckDB write per ticker per flush interval, not per push.
Canonical daily surface is updated only by the 15:45 ET merger job (surface_merger.py).

PUBLIC API
----------
    IVStreamerCollector(client, atm_map)

    IVStreamerCollector.start(trade_date)   — blocking; runs until stop() or market close
    IVStreamerCollector.stop()              — signal graceful shutdown
    IVStreamerCollector.get_snapshot()      — returns current in-memory IV dict

    run_streamer(client, atm_map, trade_date)  — convenience one-liner
"""

from __future__ import annotations

import json
import logging
import threading
import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Optional

import duckdb
import websocket  # websocket-client library

from core.shared.data_layer.iv_term_history import (
    get_iv_history_db_path,
    initialize_iv_intraday_stream_table,
    append_intraday_stream_rows,
    get_intraday_stream_summary,
)
from scan_engine.iv_collector.contract_builder import AtmBucketInfo

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

FLUSH_INTERVAL_SEC: int = 60          # Write accumulated IV updates to DuckDB every N seconds
FLUSH_BUFFER_MAX: int = 500           # Trigger early flush if pending row count exceeds this
RECONNECT_BASE_DELAY: float = 2.0     # Initial reconnect backoff
RECONNECT_MAX_DELAY: float = 60.0     # Cap backoff at 60s
HEARTBEAT_TIMEOUT_SEC: int = 35       # Disconnect assumed dead if no heartbeat > 35s
PING_INTERVAL_SEC: int = 20           # Send WebSocket ping every 20s

# ATM drift re-subscription
ATM_REFRESH_INTERVAL_MIN: int = 30   # Check for ATM drift every N minutes
ATM_DRIFT_THRESHOLD_PCT: float = 0.5 # Re-subscribe if spot moved > 0.5% from last known spot

# LEVELONE_OPTIONS field IDs
FIELD_VOLATILITY = "10"   # Implied volatility (the field we care most about)
FIELD_DELTA      = "28"
FIELD_DTE        = "27"
FIELD_OI         = "9"
FIELD_VOLUME     = "8"

# Schwab streamer request IDs
_REQ_ID_COUNTER = 0


def _next_req_id() -> int:
    global _REQ_ID_COUNTER
    _REQ_ID_COUNTER += 1
    return _REQ_ID_COUNTER


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class IVUpdate:
    """A single IV push from the streamer for one option contract."""
    symbol:    str          # Schwab streamer symbol e.g. "AAPL  260225C00265000"
    ticker:    str          # Underlying equity (parsed from symbol)
    bucket:    int          # Maturity bucket (e.g. 30)
    iv:        float        # Implied volatility (Schwab field 10)
    delta:     Optional[float] = None
    dte:       Optional[int]   = None
    oi:        Optional[int]   = None
    received_at: datetime  = field(default_factory=datetime.now)


# ---------------------------------------------------------------------------
# Streamer collector
# ---------------------------------------------------------------------------

class IVStreamerCollector:
    """
    WebSocket-based real-time IV collector for ATM option contracts.

    Parameters
    ----------
    client : SchwabClient
        Authenticated Schwab API client (used to get streamer credentials).
    atm_map : dict[str, dict[int, AtmBucketInfo]]
        Output of find_atm_for_buckets_with_ticker() for all tickers.
        Keyed by ticker → {bucket_days → AtmBucketInfo}.
    flush_interval_sec : int
        Seconds between DuckDB flush operations.
    write_to_db : bool
        If False, collect IV updates in memory only (useful for testing).
    buckets_to_stream : list[int]
        Which maturity buckets to subscribe (default: [7, 30, 60, 90]).
        The 30-day bucket is always included.
    """

    def __init__(
        self,
        client,
        atm_map: dict[str, dict[int, AtmBucketInfo]],
        *,
        flush_interval_sec: int = FLUSH_INTERVAL_SEC,
        write_to_db: bool = True,
        buckets_to_stream: Optional[list[int]] = None,
    ):
        self._client          = client
        self._atm_map         = atm_map
        self._flush_interval  = flush_interval_sec
        self._write_to_db     = write_to_db
        self._buckets         = set(buckets_to_stream or [7, 30, 60, 90])
        self._buckets.add(30)  # 30d is always mandatory

        # Build symbol → (ticker, bucket) reverse lookup (protected by _symbol_map_lock)
        self._symbol_map: dict[str, tuple[str, int]] = {}
        self._symbol_map_lock = threading.Lock()
        for ticker, bucket_map in atm_map.items():
            for bucket, info in bucket_map.items():
                if bucket in self._buckets and info.streamer_call:
                    self._symbol_map[info.streamer_call] = (ticker, bucket)

        # Last known spot price per ticker (used for ATM drift detection)
        self._spot_map: dict[str, float] = {}

        # Per-ticker chain cache: ticker → callExpDateMap (reused by refresh thread)
        self._chain_map: dict[str, dict] = {}

        # In-memory IV snapshot: ticker → bucket → latest IV
        self._iv_snapshot: dict[str, dict[int, float]] = defaultdict(dict)

        # Pending rows to flush — list of raw dicts for iv_intraday_stream
        self._pending: list[dict] = []
        self._pending_lock = threading.Lock()

        # Control
        self._running = False
        self._ws: Optional[websocket.WebSocketApp] = None
        self._last_heartbeat = time.time()
        self._trade_date: Optional[date] = None

        logger.info(
            "IVStreamerCollector initialized: %d tickers, %d symbols, buckets=%s",
            len(atm_map), len(self._symbol_map), sorted(self._buckets),
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def start(self, trade_date: Optional[date] = None) -> None:
        """
        Start the streamer loop. Blocks until stop() is called or market closes.

        Parameters
        ----------
        trade_date : date, optional
            Date to label DuckDB writes (defaults to today).
        """
        self._trade_date = trade_date or date.today()
        self._running = True

        if not self._symbol_map:
            logger.warning("No streamer symbols to subscribe — atm_map may be empty. Exiting.")
            return

        # Start the DuckDB flush background thread
        flush_thread = threading.Thread(target=self._flush_loop, daemon=True, name="IVFlush")
        flush_thread.start()

        # Start the ATM drift refresh background thread
        atm_thread = threading.Thread(target=self._atm_refresh_loop, daemon=True, name="IVATMRefresh")
        atm_thread.start()

        # Connect with automatic reconnect
        attempt = 0
        delay = RECONNECT_BASE_DELAY

        while self._running:
            attempt += 1
            logger.info("Streamer connect attempt %d...", attempt)
            try:
                streamer_info = self._client.get_streamer_info()
                self._connect(streamer_info)
            except Exception as exc:
                logger.error("Streamer connection error: %s", exc)

            if not self._running:
                break

            logger.info("Reconnecting in %.1fs...", delay)
            time.sleep(delay)
            delay = min(delay * 2, RECONNECT_MAX_DELAY)

        logger.info("IVStreamerCollector stopped.")

    def stop(self) -> None:
        """Signal the streamer to shut down gracefully."""
        self._running = False
        if self._ws:
            try:
                self._ws.close()
            except Exception:
                pass

    def get_snapshot(self) -> dict[str, dict[int, float]]:
        """
        Return current in-memory IV values.

        Returns
        -------
        dict[ticker, dict[bucket_days, iv_float]]
        """
        return dict(self._iv_snapshot)

    def store_chain_data(self, ticker: str, chain_data: dict) -> None:
        """
        Store raw Schwab /chains response for a ticker so the ATM refresh
        thread can recompute symbols without a live API call.

        Called by rest_collector after each chain fetch.

        Parameters
        ----------
        ticker : str
            Equity symbol.
        chain_data : dict
            Raw JSON response from Schwab /chains (must contain callExpDateMap).
        """
        self._chain_map[ticker] = chain_data

    # ------------------------------------------------------------------
    # WebSocket connection
    # ------------------------------------------------------------------

    def _connect(self, streamer_info: dict) -> None:
        """Open WebSocket, authenticate, subscribe, and run until disconnect."""
        url = streamer_info["streamerSocketUrl"]
        logger.info("Connecting to Schwab streamer: %s", url)

        self._ws = websocket.WebSocketApp(
            url,
            on_open=lambda ws: self._on_open(ws, streamer_info),
            on_message=self._on_message,
            on_error=self._on_error,
            on_close=self._on_close,
        )
        # run_forever blocks until disconnected
        self._ws.run_forever(
            ping_interval=PING_INTERVAL_SEC,
            ping_timeout=10,
        )

    def _on_open(self, ws: websocket.WebSocketApp, streamer_info: dict) -> None:
        """Send LOGIN then SUBS requests immediately after connect."""
        logger.info("WebSocket connected — sending LOGIN...")
        login_req = {
            "requests": [{
                "service": "ADMIN",
                "requestid": str(_next_req_id()),
                "command": "LOGIN",
                "SchwabClientCustomerId": streamer_info["schwabClientCustomerId"],
                "SchwabClientCorrelId":   streamer_info["schwabClientCorrelId"],
                "parameters": {
                    "Authorization":   self._client._get_access_token(),
                    "SchwabClientChannel":     streamer_info["schwabClientChannel"],
                    "SchwabClientFunctionId":  streamer_info["schwabClientFunctionId"],
                },
            }]
        }
        ws.send(json.dumps(login_req))

    def _send_subscription(self, ws: websocket.WebSocketApp) -> None:
        """Subscribe to LEVELONE_OPTIONS for all ATM symbols."""
        with self._symbol_map_lock:
            symbols = list(self._symbol_map.keys())
        # Subscribe in batches of 50 (Schwab limit per request)
        batch_size = 50
        for i in range(0, len(symbols), batch_size):
            batch = symbols[i:i + batch_size]
            sub_req = {
                "requests": [{
                    "service": "LEVELONE_OPTIONS",
                    "requestid": str(_next_req_id()),
                    "command": "SUBS",
                    "parameters": {
                        "keys":   ",".join(batch),
                        "fields": f"0,1,{FIELD_VOLUME},{FIELD_OI},{FIELD_VOLATILITY},{FIELD_DTE},{FIELD_DELTA}",
                    },
                }]
            }
            ws.send(json.dumps(sub_req))
            logger.debug("Subscribed %d LEVELONE_OPTIONS symbols (batch %d)", len(batch), i // batch_size + 1)

    def _on_message(self, ws: websocket.WebSocketApp, raw: str) -> None:
        """Parse incoming frame and route to handler."""
        try:
            frame = json.loads(raw)
        except json.JSONDecodeError:
            logger.debug("Non-JSON frame received: %s...", raw[:80])
            return

        # Heartbeat frame — no response needed
        if "notify" in frame:
            self._last_heartbeat = time.time()
            return

        # Response frames (LOGIN reply, SUBS confirmation)
        if "response" in frame:
            for resp in frame["response"]:
                service = resp.get("service", "")
                code    = resp.get("content", {}).get("code", -1)
                msg     = resp.get("content", {}).get("msg", "")

                if service == "ADMIN" and code == 0:
                    logger.info("LOGIN successful — subscribing to %d options symbols...", len(self._symbol_map))
                    self._send_subscription(ws)
                elif service == "ADMIN":
                    logger.error("LOGIN failed: code=%s msg=%s", code, msg)
                    self._running = False
                    ws.close()
                elif code == 0:
                    logger.debug("SUBS confirmed for %s", service)
                else:
                    logger.warning("Response: service=%s code=%s msg=%s", service, code, msg)
            return

        # Data frames — the main payload
        if "data" in frame:
            for data_item in frame["data"]:
                if data_item.get("service") != "LEVELONE_OPTIONS":
                    continue
                for content in data_item.get("content", []):
                    self._process_option_update(content)

    def _process_option_update(self, content: dict) -> None:
        """Extract IV from a LEVELONE_OPTIONS content item and buffer it."""
        symbol = content.get("key", "")
        with self._symbol_map_lock:
            lookup = self._symbol_map.get(symbol)
        if lookup is None:
            return  # Not one of our tracked symbols

        ticker, bucket = lookup

        raw_iv = content.get(FIELD_VOLATILITY)
        if raw_iv is None:
            return  # No IV in this push (push-on-change; only changed fields present)

        try:
            iv = float(raw_iv)
        except (TypeError, ValueError):
            return
        if iv <= 0:
            return  # Schwab sentinel or zero

        # Buffer the update
        overflow = False
        with self._pending_lock:
            self._pending.append({
                "ticker":     ticker,
                "ts":         datetime.utcnow(),
                "trade_date": self._trade_date or date.today(),
                "bucket":     bucket,
                "iv":         iv,
                "source":     "schwab_streamer",
                "atm_symbol": symbol,
            })
            self._iv_snapshot[ticker][bucket] = iv
            if len(self._pending) >= FLUSH_BUFFER_MAX:
                overflow = True

        logger.debug("[%s] bucket=%dd IV=%.2f%% (symbol=%s)", ticker, bucket, iv, symbol)

        if overflow:
            logger.info("Buffer overflow (%d rows) — triggering early flush", FLUSH_BUFFER_MAX)
            self._flush_pending()

    def _on_error(self, ws: websocket.WebSocketApp, error: Exception) -> None:
        logger.error("WebSocket error: %s", error)

    def _on_close(self, ws: websocket.WebSocketApp, close_status_code, close_msg) -> None:
        logger.info("WebSocket closed (code=%s msg=%s)", close_status_code, close_msg)
        # Flush on disconnect so we don't lose buffered data between reconnects
        self._flush_pending()

    # ------------------------------------------------------------------
    # ATM drift detection and re-subscription
    # ------------------------------------------------------------------

    def _atm_refresh_loop(self) -> None:
        """
        Background thread: periodically re-check ATM strikes for all tracked tickers.

        Runs every ATM_REFRESH_INTERVAL_MIN minutes. For each ticker:
          1. Fetch current spot via SchwabClient.get_quote()
          2. If spot has moved > ATM_DRIFT_THRESHOLD_PCT from last known spot →
             re-fetch chain, recompute ATM symbols
          3. UNSUBS old symbols, SUBS new symbols (if WebSocket is live)
          4. Update _symbol_map atomically under _symbol_map_lock
        """
        interval_sec = ATM_REFRESH_INTERVAL_MIN * 60
        # Initial wait — let the streamer connect and subscribe first
        time.sleep(interval_sec)

        while self._running:
            try:
                self._refresh_atm_symbols()
            except Exception as exc:
                logger.warning("ATM refresh error (non-fatal): %s", exc)
            time.sleep(interval_sec)

    def _refresh_atm_symbols(self) -> None:
        """
        Re-evaluate ATM symbols for all tickers and patch subscriptions if drift detected.
        """
        from scan_engine.iv_collector.contract_builder import find_atm_for_buckets_with_ticker
        from scan_engine.iv_collector.chain_surface import fetch_chain

        tickers = list(self._atm_map.keys())
        if not tickers:
            return

        refreshed = 0
        for ticker in tickers:
            if not self._running:
                break
            try:
                # Fetch current spot price
                quote = self._client.get_quote(ticker)
                if not quote:
                    continue
                spot = float(quote.get("lastPrice") or quote.get("last") or 0)
                if spot <= 0:
                    continue

                last_spot = self._spot_map.get(ticker)
                self._spot_map[ticker] = spot

                if last_spot is None:
                    # First time — no drift to measure
                    continue

                drift_pct = abs(spot - last_spot) / last_spot * 100
                if drift_pct < ATM_DRIFT_THRESHOLD_PCT:
                    logger.debug(
                        "[%s] ATM drift %.3f%% < threshold %.1f%% — no resubscription needed",
                        ticker, drift_pct, ATM_DRIFT_THRESHOLD_PCT,
                    )
                    continue

                logger.info(
                    "[%s] ATM drift detected: spot %.2f → %.2f (%.2f%%) — refreshing subscriptions",
                    ticker, last_spot, spot, drift_pct,
                )

                # Re-fetch chain (use cached structural chain if available, else live)
                chain_data = self._chain_map.get(ticker)
                if chain_data is None:
                    # Fallback: fetch fresh chain
                    surface = fetch_chain(self._client, ticker, spot)
                    if surface is None:
                        logger.warning("[%s] ATM refresh: chain fetch returned None", ticker)
                        continue
                    # We only have surface row, not raw chain — skip symbol refresh
                    # (chain data is stored at rest_collector level; signal for re-run)
                    logger.info(
                        "[%s] ATM refresh: no cached chain available — "
                        "resubscription deferred to next REST collection",
                        ticker,
                    )
                    continue

                # Recompute ATM from cached chain
                call_map = chain_data.get("callExpDateMap", {})
                new_bucket_map = find_atm_for_buckets_with_ticker(
                    ticker, call_map, spot, list(self._buckets),
                )

                if not new_bucket_map:
                    logger.warning("[%s] ATM refresh: no ATM found for new spot %.2f", ticker, spot)
                    continue

                # Identify old symbols for this ticker to UNSUBS
                with self._symbol_map_lock:
                    old_symbols = [
                        sym for sym, (t, _) in self._symbol_map.items() if t == ticker
                    ]
                    # Build new symbol set
                    new_symbols: list[str] = []
                    for bucket, info in new_bucket_map.items():
                        if bucket in self._buckets and info.streamer_call:
                            new_symbols.append(info.streamer_call)

                    # Compute changes
                    old_set = set(old_symbols)
                    new_set = set(new_symbols)
                    to_remove = old_set - new_set
                    to_add    = new_set - old_set

                    if not to_remove and not to_add:
                        logger.debug("[%s] ATM refresh: symbols unchanged for new spot %.2f", ticker, spot)
                        continue

                    # Update atm_map for this ticker
                    self._atm_map[ticker] = new_bucket_map

                    # Update symbol_map: remove old, add new
                    for sym in to_remove:
                        self._symbol_map.pop(sym, None)
                    for bucket, info in new_bucket_map.items():
                        if bucket in self._buckets and info.streamer_call:
                            self._symbol_map[info.streamer_call] = (ticker, bucket)

                # Send UNSUBS + SUBS via live WebSocket (if connected)
                ws = self._ws
                if ws and ws.sock and ws.sock.connected:
                    if to_remove:
                        self._send_unsubs(ws, list(to_remove))
                    if to_add:
                        self._send_subs(ws, list(to_add))

                logger.info(
                    "[%s] ATM resubscription complete: removed=%d added=%d new_spot=%.2f",
                    ticker, len(to_remove), len(to_add), spot,
                )
                refreshed += 1

            except Exception as exc:
                logger.warning("[%s] ATM refresh error: %s", ticker, exc)

        if refreshed > 0:
            logger.info("ATM refresh cycle complete: %d tickers resubscribed", refreshed)

    def _send_unsubs(self, ws: websocket.WebSocketApp, symbols: list[str]) -> None:
        """Send LEVELONE_OPTIONS UNSUBS for the given symbols."""
        for i in range(0, len(symbols), 50):
            batch = symbols[i:i + 50]
            req = {
                "requests": [{
                    "service": "LEVELONE_OPTIONS",
                    "requestid": str(_next_req_id()),
                    "command": "UNSUBS",
                    "parameters": {"keys": ",".join(batch)},
                }]
            }
            try:
                ws.send(json.dumps(req))
                logger.debug("UNSUBS %d options symbols", len(batch))
            except Exception as exc:
                logger.warning("UNSUBS send failed: %s", exc)

    def _send_subs(self, ws: websocket.WebSocketApp, symbols: list[str]) -> None:
        """Send LEVELONE_OPTIONS SUBS for the given symbols."""
        for i in range(0, len(symbols), 50):
            batch = symbols[i:i + 50]
            req = {
                "requests": [{
                    "service": "LEVELONE_OPTIONS",
                    "requestid": str(_next_req_id()),
                    "command": "SUBS",
                    "parameters": {
                        "keys":   ",".join(batch),
                        "fields": f"0,1,{FIELD_VOLUME},{FIELD_OI},{FIELD_VOLATILITY},{FIELD_DTE},{FIELD_DELTA}",
                    },
                }]
            }
            try:
                ws.send(json.dumps(req))
                logger.debug("SUBS %d options symbols", len(batch))
            except Exception as exc:
                logger.warning("SUBS send failed: %s", exc)

    # ------------------------------------------------------------------
    # DuckDB flush
    # ------------------------------------------------------------------

    def _flush_loop(self) -> None:
        """Background thread: flush pending IV updates to DuckDB every N seconds."""
        while self._running:
            time.sleep(self._flush_interval)
            self._flush_pending()

        # Final flush on shutdown
        self._flush_pending()

    def _flush_pending(self) -> None:
        """
        Write buffered IV pushes to iv_intraday_stream (NOT iv_term_history).

        The canonical daily surface is updated only by the 15:45 merger job.
        This preserves auditability, fallback integrity, and backtesting correctness.
        """
        with self._pending_lock:
            if not self._pending:
                return
            rows = list(self._pending)
            self._pending.clear()

        if not self._write_to_db:
            logger.debug("DB write skipped (write_to_db=False): %d rows buffered", len(rows))
            return

        db_path = get_iv_history_db_path()
        try:
            con = duckdb.connect(str(db_path), read_only=False)
            initialize_iv_intraday_stream_table(con)
            append_intraday_stream_rows(con, rows)
            con.close()
            logger.info(
                "Streamer flush → iv_intraday_stream: %d rows (tickers=%d) for %s",
                len(rows),
                len({r["ticker"] for r in rows}),
                self._trade_date,
            )
        except Exception as exc:
            logger.error("Streamer DuckDB flush failed: %s", exc)
            # Re-buffer on failure so data is not lost
            with self._pending_lock:
                self._pending = rows + self._pending


# ---------------------------------------------------------------------------
# Convenience entry point
# ---------------------------------------------------------------------------

def run_streamer(
    client,
    atm_map: dict[str, dict[int, AtmBucketInfo]],
    *,
    trade_date: Optional[date] = None,
    write_to_db: bool = True,
    flush_interval_sec: int = FLUSH_INTERVAL_SEC,
) -> IVStreamerCollector:
    """
    Create and start an IVStreamerCollector in a background thread.

    The returned collector object can be used to call stop() or get_snapshot().

    Parameters
    ----------
    client : SchwabClient
        Authenticated Schwab API client.
    atm_map : dict[str, dict[int, AtmBucketInfo]]
        ATM contract map from find_atm_for_buckets_with_ticker().
    trade_date : date, optional
        Date label for DuckDB writes.
    write_to_db : bool
        Persist to DuckDB (default True).
    flush_interval_sec : int
        DuckDB flush frequency.

    Returns
    -------
    IVStreamerCollector
        Running collector instance.
    """
    collector = IVStreamerCollector(
        client,
        atm_map,
        write_to_db=write_to_db,
        flush_interval_sec=flush_interval_sec,
    )
    thread = threading.Thread(
        target=collector.start,
        kwargs={"trade_date": trade_date},
        daemon=True,
        name="IVStreamer",
    )
    thread.start()
    logger.info("IVStreamerCollector started in background thread.")
    return collector
